// <auto-generated />
using System;
using Manage_KPI_or_OKR_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manage_KPI_or_OKR_System.Migrations
{
    [DbContext(typeof(MiniERPDbContext))]
    [Migration("20260419203140_AddKpiMetadataAndReportIncidents")]
    partial class AddKpiMetadataAndReportIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.AIGenerationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("AIGenerationHistories");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.AdhocTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AdditionalKPI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AssignDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TaskName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AdhocTasks");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImpactedTable")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.BonusRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BonusPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("BonusRules");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.CheckInDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AchievedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CheckInId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpectedValueAtDeadline")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProgressPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ScheduleProgressPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.ToTable("CheckInDetails");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.CheckInHistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckInId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.ToTable("CheckInHistoryLogs");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.CheckInStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasFilter("[StatusName] IS NOT NULL");

                    b.ToTable("CheckInStatuses");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasFilter("[DepartmentCode] IS NOT NULL");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("StrategicGoalId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasFilter("[EmployeeCode] IS NOT NULL");

                    b.HasIndex("SystemUserId")
                        .IsUnique()
                        .HasFilter("[SystemUserId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EmployeeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId");

                    b.ToTable("EmployeeAssignments");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSystemProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PeriodType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("EvaluationPeriods");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationReportIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("EvaluationReportIncidents");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationReportSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EvaluationReportSummaries");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DirectorReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DirectorReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DirectorReviewedById")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("RankId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SubmissionStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorReviewedById");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("RankId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.FailReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReasonName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FailReasons");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.GoalComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckInId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("CommenterId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KPIId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.HasIndex("CommenterId");

                    b.HasIndex("KPIId");

                    b.ToTable("GoalComments");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.GradingRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("MinScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RankCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("GradingRanks");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.HRExportReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExportDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExporterId")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("ReportFileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("HRExportReports");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KPIName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("KPITypeId")
                        .HasColumnType("int");

                    b.Property<int?>("OKRId")
                        .HasColumnType("int");

                    b.Property<int?>("OKRKeyResultId")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignerId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("KPITypeId");

                    b.HasIndex("OKRId");

                    b.HasIndex("OKRKeyResultId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StatusId");

                    b.ToTable("KPIs");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPIAdjustmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdjusterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KPIId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NewValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdjusterId");

                    b.HasIndex("KPIId");

                    b.ToTable("KPIAdjustmentHistories");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPICheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FailReasonId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsLate")
                        .HasColumnType("bit");

                    b.Property<int?>("KPIId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("ReviewScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("SubmittedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FailReasonId");

                    b.HasIndex("KPIId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("KPICheckIns");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPIDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("CheckInDeadlineTime")
                        .HasColumnType("time");

                    b.Property<int?>("CheckInFrequencyDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FailThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsInverse")
                        .HasColumnType("bit");

                    b.Property<int?>("KPIId")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PassThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReminderBeforeHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KPIId");

                    b.ToTable("KPIDetails");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPIProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PropertyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("KPIProperties");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPIType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasFilter("[TypeName] IS NOT NULL");

                    b.ToTable("KPITypes");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI_Department_Assignment", b =>
                {
                    b.Property<int>("KPIId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("KPIId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("KPI_Department_Assignments");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI_Employee_Assignment", b =>
                {
                    b.Property<int>("KPIId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("KPIId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("KPI_Employee_Assignments");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI_Result_Comparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CompletionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("EmployeeAchievedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FinalResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KPIId")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SystemTargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("KPIId");

                    b.HasIndex("PeriodId");

                    b.ToTable("KPI_Result_Comparisons");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.MissionVision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinancialTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MissionVisionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TargetYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("MissionVisions");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Cycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("OKRTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectiveName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OKRTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("OKRs");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKRKeyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FailReasonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInverse")
                        .HasColumnType("bit");

                    b.Property<string>("KeyResultName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OKRId")
                        .HasColumnType("int");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OKRId");

                    b.ToTable("OKRKeyResults");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKRType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasFilter("[TypeName] IS NOT NULL");

                    b.ToTable("OKRTypes");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR_Department_Allocation", b =>
                {
                    b.Property<int>("OKRId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("OKRId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("OKR_Department_Allocations");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR_Employee_Allocation", b =>
                {
                    b.Property<int>("OKRId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("AllocatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OKRId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OKR_Employee_Allocations");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR_Mission_Mapping", b =>
                {
                    b.Property<int>("OKRId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("OKRId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("OKR_Mission_Mappings");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OneOnOneMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("MeetingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("OneOnOneMeetings");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PositionCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PositionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RankLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode")
                        .IsUnique()
                        .HasFilter("[PositionCode] IS NOT NULL");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.RealtimeExpectedBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpectedBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeriodId");

                    b.ToTable("RealtimeExpectedBonuses");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Role_Permission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_Permissions");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StatusType", "StatusName")
                        .IsUnique()
                        .HasFilter("[StatusType] IS NOT NULL AND [StatusName] IS NOT NULL");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.SystemAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SourceRefId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("SystemAlerts");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.SystemParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParameterCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.ToTable("SystemParameters");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.AIGenerationHistory", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.AdhocTask", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.AuditLog", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.BonusRule", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.GradingRank", null)
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.CheckInDetail", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPICheckIn", null)
                        .WithMany()
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.CheckInHistoryLog", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPICheckIn", null)
                        .WithMany()
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Department", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Employee", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EmployeeAssignment", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationReportIncident", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.EvaluationResult", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("DirectorReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.GradingRank", null)
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.GoalComment", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPICheckIn", null)
                        .WithMany()
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CommenterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.HRExportReport", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssignerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPIType", null)
                        .WithMany()
                        .HasForeignKey("KPITypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKR", null)
                        .WithMany()
                        .HasForeignKey("OKRId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKRKeyResult", null)
                        .WithMany()
                        .HasForeignKey("OKRKeyResultId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPIProperty", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPIAdjustmentHistory", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("AdjusterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPICheckIn", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.FailReason", null)
                        .WithMany()
                        .HasForeignKey("FailReasonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.CheckInStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPIDetail", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI_Department_Assignment", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI_Employee_Assignment", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.KPI_Result_Comparison", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.KPI", null)
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.MissionVision", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKRType", null)
                        .WithMany()
                        .HasForeignKey("OKRTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKRKeyResult", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKR", null)
                        .WithMany("KeyResults")
                        .HasForeignKey("OKRId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR_Department_Allocation", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKR", null)
                        .WithMany()
                        .HasForeignKey("OKRId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR_Employee_Allocation", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKR", null)
                        .WithMany()
                        .HasForeignKey("OKRId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR_Mission_Mapping", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.MissionVision", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manage_KPI_or_OKR_System.Models.OKR", null)
                        .WithMany()
                        .HasForeignKey("OKRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OneOnOneMeeting", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.RealtimeExpectedBonus", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Role", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.Role_Permission", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.SystemAlert", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.SystemParameter", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.SystemUser", b =>
                {
                    b.HasOne("Manage_KPI_or_OKR_System.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Manage_KPI_or_OKR_System.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Manage_KPI_or_OKR_System.Models.OKR", b =>
                {
                    b.Navigation("KeyResults");
                });
#pragma warning restore 612, 618
        }
    }
}
